### PR TITLE
Add the SciPy and NumPy ideas pages

### PR DESCRIPTION
**Pull request by rgommers**

### CODE REVIEW

**Comment by mikofski** [comment]
~See [scipy-gh7168](https://github.com/scipy/scipy/issues/7168) for a list of SciPy doc strings that need examples~

**Comment by rgommers** [comment]
> See scipy-gh7168 for a list of SciPy doc strings that need examples

That's not really what a tech writer should do. It's a great task to give to new contributors, if we get a tech writer they can do more valuable things

**Comment by kain88-de** [comment]
thanks. Who will be the two mentors for scipy and numpy. According to GSoD rules we need at least two mentors per accepted project.

**Comment by rgommers** [comment]
We have mentors, at least @chrisb83 for SciPy, @mattip for NumPy and myself for both. I looked at the GSoD instructions but it didn't say to add names. Where would you prefer me to add them?

**Comment by kain88-de** [comment]
Mostly for our own bookkeeping. We need to ensure enough mentors are
available.

**Comment by rgommers** [comment]
Okay, then leave it at these names for now - we have more mentors if needed. Will depend on the type of project; many devs are enthusiastic about GSoD but specialize in one or a couple of modules.

**Comment by chrisb83** [comment]
@pvanmulbregt also said he can be a mentor for SciPy.stats

**Comment by pvanmulbregt** [comment]
Confirming that I did indeed say that.

**Comment by rgommers** [comment]
Thanks Paul.

**Comment by rgommers** [comment]
@chrisb83 @pvanmulbregt @ev-br @larsoner it looks like I can only be a primary admin for one project, and I signed up for NumPy already. **Does one of you want to sign up for SciPy?**

It should be very little work - I can provide all the answers for the [application form](https://developers.google.com/season-of-docs/docs/admin-guide), and I've created a google group for numpy and scipy combined (numpy-scipy-gsod@googlegroups.com) to reply to any inquiries so I can still do that. Just need someone to sign up. Or ideally 2 people, one as the backup - I think I can do that for SciPy but I'm not 100% sure.

**Comment by kain88-de** [comment]
Hi Ralf

If you do not find anyone in time we can also do the signup as admin and/or
backup admin for SciPy.

Best Max

**Comment by chrisb83** [comment]
I registered as a mentor for SciPy. Since I am travelling at the moment, I hope someone else can sign up as an admin.

**Comment by rgommers** [comment]
@kain88-de hi Max, it seems we're struggling to find a second admin. I'd like to take you up on your offer. I'll email Sam and yourself.

**Comment by rgommers** [comment]
thanks for the reply @chrisb83

**Comment by kain88-de** [comment]
Sure I’ll can do this tomorrow morning European time.

**Comment by rgommers** [comment]
Awesome, thanks!

**Pull request merged**
