### PR TITLE
Blosc ideas

### PR DESCRIPTION
**Pull request by FrancescAlted**
To Blosc developers:  please feel free to suggest changes or improvements on this draft.  Thanks!

### CODE REVIEW

**Comment by kain88-de** [comment]
Hi, @FrancescAlted are there any similar libraries you can use as documentation example?

Also keep in mind google expects at least two mentors per accepted project.

**Comment by kain88-de** [comment]
@FrancescAlted feel free to merge this once you find a second mentor. We can afterwards update the main page.

**Comment by FrancescAlted** [comment]
Hi @kain88-de .  I addressed the suggestions in the new version; in particular, we have a second mentor.  Merging.

**Comment by FrancescAlted** [comment]
Oops, it seems that I don't have write access permissions.  @kain88-de  could you do the merge yourself?  Thanks!

**Comment by kain88-de** [comment]
Hm weird I cannot merge on my phone

**Comment by FrancescAlted** [comment]
@kain88-de Great, the merge worked.  Just make sure that you grant me write access to this repo; we may want to continue improving this during the weekend.

**Comment by FrancescAlted** [comment]
@kain88-de Sorry, I missed the invitation for getting write privileges.  All should be fine now.  Thanks!

**Pull request merged**
